spring.application.name=file storage

server.error.path=/error
server.port=8081

spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/storage?authSource=admin
spring.data.mongodb.database=storage
spring.data.mongodb.gridfs.bucket=test

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

application.security.jwt.secret-key="wBgwijSjLma8zXulSq3Mg8ZSruYPtWJkkcwFXyse9peL9hCueXSJGBanDTlN5aZrgDfOTiPJZ9RK"
application.security.jwt.expiration=86400000

spring.devtools.restart.enabled=false

logging.level.org.springframework.aop=DEBUG
logging.level.com.brightobra.file.storage.configuration.aop=DEBUG
logging.level.org.springframework.security=TRACE